version: '3'
services:
  app:
    ports:
      - "80:80"
    build: ./docker/app
    container_name: gakushucho_app
    volumes:
      - ./src:/var/www/html
  db:
    image: mysql:5.7
    container_name: gakushucho_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gakushucho_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_pass
      TZ: 'Asia/Tokyo'
    command: mysqld --charcter-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306